export const CDP_MOUNT_ATTACH_MS = 12_000
export const CDP_MOUNT_SETTLE_MS = 4_000
// PLATFORM§8
export const CDP_GUEST_ID_RETRY_MS = 100
export const CDP_GUEST_ID_RETRIES = 20

const IPC_AND_BUSY_RENDER_LOOP_HEADROOM_MS = 4_000

export const CDP_OP_BUDGET_MS =
  CDP_MOUNT_ATTACH_MS +
  CDP_MOUNT_SETTLE_MS +
  CDP_GUEST_ID_RETRY_MS * CDP_GUEST_ID_RETRIES +
  IPC_AND_BUSY_RENDER_LOOP_HEADROOM_MS
